core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

makanyu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pesan_makanan/', include('pesan_makanan.urls')),
    path('', include('homepage.urls')),
    path('menu/', include('menu.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('menumakan/', views.menumakan, name='menumakan'),
    path('create/', views.menu_create, name='menu_create')
    ]

menu/models.py
from django.db import models
# from django.contrib.auth.models import User
# Create your models here.
class Menu(models.Model):
	name = models.CharField(max_length=30)
	price = models.PositiveIntegerField()
	image = models.ImageField(upload_to='images/')

	def __str__(self):
		return self.name

class MenuDipesan(models.Model):
	menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
	amount = models.PositiveSmallIntegerField()

	def __str__(self):
		return str(self.menu)

class Pesan(models.Model):
    menu = models.ManyToManyField(MenuDipesan)

menu/forms.py
from django import forms
from .models import Menu

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['name', 'price','image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class PesanForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for menu in Menu.objects.all():
			self.fields['menu_' + str(menu.id)] = forms.IntegerField(
				min_value=0,
				max_value=32767,
				initial=0,
			)

menu/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .models import Menu, Pesan, MenuDipesan
from django.urls import reverse
from . import forms

def menumakan(request):
	if request.method == 'POST':
		form_pesanan = forms.PesanForm(request.POST)
		if form_pesanan.is_valid():
			pesanan = Pesan()
			pesanan.save()
			counter = 0
			for key, value in form_pesanan.cleaned_data.items():
				if key[:5] == 'menu_' and value > 0:
					counter += 1
					menu_dipesan = MenuDipesan(menu=Menu.objects.get(id=int(key[5:])),
						amount=value)
					menu_dipesan.save()
					pesanan.menu.add(menu_dipesan)
			if counter != 0:
				return redirect(reverse('pesan_makanan:pesan_makanan'))
	else:
		form_pesanan = forms.PesanForm()

	semua_menu = Menu.objects.all()
	for menu in semua_menu:
		menu.form_field = form_pesanan['menu_' + str(menu.id)]

	return render(request, 'menumakan.html', {'menus':semua_menu, 'form_pesanan': form_pesanan})

def menu_create(request):
    form = forms.MenuForm(request.POST, request.FILES) 
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('menu:menumakan')
    else:
        form = forms.MenuForm()
    return render(request, 'menu_create.html', {'form': form})

menu/templates/menu_create.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% block content %}
<body style="background-image: url('{% static 'image/background.png'%}')">

<div class="menu">
    <p class="font text-center" id="judul">Create Menu</p>
    <form action="{% url 'menu:menu_create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
                    <div class="col-sm-1"></div>
                        <div class="form-group col-sm-10">
                            {% for fields in form %}
                                {{ fields.label_tag }}
                                    <br>
                                {{ fields }}
                            {% endfor %}
                        </div>
                    </div>
                <div class="form-row">
            <div class="col-sm-1"></div>
        <input type="file" name="myfile">
        <input type="submit" class="btn btn-primary float-right" value="Submit">
    </form>      
</div>
</body>

{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

menu/templates/menumakan.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="row p-4">
    <div class = "col-md-12">
        <h1 id="judul">Ayam Penyet Strike</h1>
        <h2 id="text1">Spesialis Ayam Penyet</h2>
        <h2 id="text2">Jalan Akses UI No. 32 Depok, Jawa Barat</h2>
   </div>
</div>

<div class="row p-4">
    <div class="col-md-4">
        <img id="foto" src="{% static 'image/ayam-rica-rica.jpg' %}" width="300" height="200">
    </div>
    <div class="col-md-4">
        <img id="foto2" src="{% static 'image/ayam-goreng-mentega.jpg' %}" width="300" height="200">
    </div>
    <div class="col-md-4">
        <img align="left" src="{% static 'image/ayam-bakar-taliwang.jpg' %}" width="300" height="200">
    </div>
</div>
 
<div class="row p-4" id="menu">
    <div class="col-md-1 btn-group btn-group-toggle" data-toggle="buttons">
        <label class=" btn btn-warning active">
            <input type="radio" name="options" id="option1">Menu</input>
        </label>
        <label class="btn btn-default active">
            <input type="radio" name="options" id="option2">Antrian</input>
        </label>
    </div>
</div>

<a href="{% url 'menu:menumakan' %}"></a>
<div class="d-flex justify-content-center w-100 row text-center">
    <h1 id="judul">MENU</h1>
</div>
<div class="col-md-12 text-center">
    {% if menus %}
    <form action="" method="POST">
    <table style="font-size: 30px" cellpadding="70" border="0">
        <thead>
            <th style=" padding-top: 40px;padding-bottom: 0px">Name</th>
            <th style=" padding-top: 40px; padding-bottom: 0px">Price</th>
        </thead>
        <tbody>
                {% csrf_token %}
                {% for menumakan in menus %}
                <div class="col-sm-4 text-center">
                    <tr>
                    <td> {{ menumakan.name }} </td>
                    <td> {{ menumakan.price }} </td>
                    <td> <img style="width: 300px" class="images"src="{{ menumakan.image.url }}"> </td>
                    <td>{{ menumakan.form_field }}</td>
                    </tr>
                </div>
                {% endfor %}
        </tbody>
    </table>
    <div class = 'col-md-12'>
        <div class = "w-100 d-flex justify-content-center form-group">
            <button class="btn btn-primary" type="submit" >Pesan</button>
        </div>
    </div>
    </form>
    {% else %}
    <div class="no-menu margin-small">
        <h2>There's no menu yet</h2>
    </div>
    {% endif %}
</div>
{% endblock %}