core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'


urlpatterns = [
    path('', views.home, name='home'),
]

makanyu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pesan_makanan/', include('pesan_makanan.urls')),
    path('', include('homepage.urls')),
    path('menu/', include('menu.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('menumakan/', views.menumakan, name='menumakan'),
    path('create/', views.menu_create, name='menu_create')
    ]

homepage/models.py
from django.db import models

# Create your models here.

class Restaurant(models.Model):
    nama = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=50)
    alamat = models.CharField(max_length=50)
    gambar = models.ImageField(upload_to='images/')

    

    def __str__(self):
        return self.nama
        

homepage/forms.py
from django import forms
from .models import Restaurant

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['nama', 'deskripsi', 'alamat', 'gambar']
        labels  = {
        'nama':'Nama Restoran', 
        'deskripsi':'Deskripsi Restoran', 
        'alamat':'Alamat Restoran', 
        'gambar':'Foto Restoran',
        }

        widgets = {
        'nama' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text', 'placeholder' : 'Rumah Makan Sederhana'}),
        'deskripsi' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text', 'placeholder' : 'Aneka Masakan Padang'}),
        'alamat' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text', 'placeholder' : 'Jl. Menuju Surga'}),

        }
    
        

homepage/views.py
from django.shortcuts import render, redirect
from .forms import RestaurantForm
from .models import Restaurant

# Create your views here.



def home(request):
    if request.method == 'POST':
        form = RestaurantForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/home')
    else:
        form = RestaurantForm()


    temp = Restaurant.objects.all()
    
    return render(request, 'home.html', {'restaurant_list': temp,
                                         'ini_restaurant_form': form,
                                         'home_page' : True,})

homepage/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content %}


        <div class="container">
          <div class="row">
            <div class="col">
              <h1 style="font-size: 50px; font-weight: bold; margin-top: 70px;"> Mengantri <br> Memang Menyebalkan.</h1>
            <h2 style="font-family: Kayak Sans; font-size: 26px; font-weight: lighter; margin-top: 30px"> Dengan Makanyu, kamu dapat memesan makanan favoritmu tanpa perlu berdiri lama untuk mengantri. Cukup satu klik lalu ambil makananmu ketika sudah matang. </h2>
                
            </div>
            <div class="col">
              <img src="{% static 'images/Artboard 1.svg' %}">
            </div>
              
          </div>
            
            
          <div class="row" style="margin-top: 160px; margin-bottom: 20px;">
              <div class="col">
                  
            <h3 style="font-size: 30px; font-weight: bold; margin-bottom: 20px;"> Daftar Tempat Makan</h3>
              </div>
              
              <div class="col">
              </div>
          </div>
            
        <div class="row" style="margin-bottom: 25px;">
            <div class="container-fluid">
              <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner row w-100 mx-auto">
                    
                    
                  <div class="carousel-item col-md-4 active">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{% static 'images/images.jpg' %}" alt="Card image cap" alt width="600px" alt height="600px"> 
                      <div class="card-body">
                        <h4 class="card-title" style="font-weight: bold">Ayam Penyet Strike</h4>
                        <p class="card-text">Spesialis Ayam Penyet <br> 
                                            Jalan Akses UI, Kelapa Dua No. 2, Cimanggis
                        </p>
                        <a href="{% url 'menu:menumakan' %}" class="btn btn-primary">Kunjungi (Klik Ini Untuk Ke Halaman Selanjutnya) </a>
                      </div>
                    </div>
                  </div>
                    
                    
                  <div class="carousel-item col-md-4">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{% static 'images/rumah-makan-putera-lombok-alam-sutera-serpong-tangerang-banten.jpg' %}" alt="Card image cap" alt width="600px" alt height="600px">
                      <div class="card-body">
                        <h4 class="card-title">Rumah Makan Putera Lombok</h4>
                        <p class="card-text"> Makanan Khas Lombok <br> Jl. Margonda Raya No. 518, Pondok Cina
                          </p>
                        <a href="#" class="btn btn-primary">Kunjungi</a>
                      </div>
                    </div>
                  </div>
                    
                    
                  <div class="carousel-item col-md-4">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{% static 'images/resizeimage.net-output-1-1.jpg' %}" alt="Card image cap" alt width="600px" alt height="600px">
                        
                      <div class="card-body">
                        <h4 class="card-title">Rumah Makan Sederhana</h4>
                        <p class="card-text">Makanan Khas Padang <br> Jl. Margonda Raya No. 280, Pondok Cina
                          </p>
                        <a href="#" class="btn btn-primary">Kunjungi</a>
                      </div>
                    </div>
                  </div>
                    
                    
                  <div class="carousel-item col-md-4">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{% static 'images/rumah-makan-bidadari-1.jpg' %}" alt="Card image cap" alt width="600px" alt height="600px">
                      <div class="card-body">
                        <h4 class="card-title">Rumah Makan Bidadari</h4>
                        <p class="card-text"> Deskripsi Rumah Makan <br> Jl. Raya Bogor KM 29 No. 32, Cimanggis
                          </p>
                        <a href="#" class="btn btn-primary">Kunjungi</a>
                      </div>
                    </div>
                  </div>
                    
                    
                  <div class="carousel-item col-md-4">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{% static 'images/HeFuShun_Restaurant.jpg' %}" alt="Card image cap" alt width="600px" alt height="600px">
                      <div class="card-body">
                        <h4 class="card-title">Restoran HeFuShun</h4>
                        <p class="card-text">Chinese Food <br> Jl. Margonda Raya No. 514, Pondok Cina
                          </p>
                        <a href="#" class="btn btn-primary">Kunjungi</a>
                      </div>
                    </div>
                  </div>
                    
                    
                  <div class="carousel-item col-md-4">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{% static 'images/c5511d65-8f4e-49af-a300-5fa43ad52b03_169.jpg' %}" alt="Card image cap" alt width="600px" alt height="600px">
                      <div class="card-body">
                        <h4 class="card-title">Pujasera Blok S</h4>
                        <p class="card-text">Jl. Margonda Raya No. 488, Pondok Cina</p>
                        <a href="#" class="btn btn-primary">Kunjungi</a>
                      </div>
                    </div>
                  </div>
                    
                    
                  <div class="carousel-item col-md-4">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{% static 'images/1881295642.jpg' %}" alt="Card image cap" alt width="600px" alt height="600px">
                      <div class="card-body">
                        <h4 class="card-title">Sate Khas Senayan</h4>
                        <p class="card-text">Deskripsi Rumah Makan <br> Jl. Akses UI No. 35, Cimanggis</p>
                        <a href="#" class="btn btn-primary">Kunjungi</a>
                      </div>
                    </div>
                  </div>
                
                  
                  {% for restaurant in restaurant_list %}
                  <div class="carousel-item col-md-4">
                    <div class="card">
                      <img class="card-img-top img-fluid" src="{{ restaurant.gambar.url }}" alt="Card image cap" alt width="600px" alt height="600px">
                      <div class="card-body">
                        <h4 class="card-title">"{{ restaurant.nama }}"</h4>
                          <p class="card-text">"{{ restaurant.deskripsi }}" <br> "{{ restaurant.alamat }}"</p>
                        <a href="#" class="btn btn-primary">Kunjungi</a>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                  
                
                <a style="left: 100px" class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                  
                <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
                  
                </div>
        
                    
                
                  
              </div>
            </div>
          </div>
        

     <div class="row">
            <div class="col">
		<h2 style="font-size: 30px; font-weight: bold; margin-top: 50px; margin-bottom: 30px;"> Daftarkan Tempat Makanmu </h2>
            </div>
            <div class="col">
         </div>
    </div>
            
            <div class = "row">
                <div class="col">
                    <form action="{% url 'homepage:home' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                        <table class="d-flex justify-content-center" style="font-size: 1.25rem;">
                        {{ ini_restaurant_form.as_table }}
                            
                    </table>

                      <div class='d-flex justify-content-center' style="margin-top: 40px; margin-bottom: 200px;">
                        <input class="btn btn-primary" type="submit" name="submit" value="Daftarkan">
                    </div>
                </form>
                    </div>
            </div>
            

</div>



{% endblock content %}